### ISSUE TITLE
npm 5 and npm run clean task failed

### ISSUE THREAD

**Issue by almothafar** [AngularClass/angular-starter#1783]
* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
It becomes a bug after npm released version 5, 

As the message said, it is clear that npm "self-heals" from corruption:
```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

```
 so you have to change the following line inside package.json:
`    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist compiled dll",`

to use `npm cache clean --force` or `npm cache verify`.

npm is so fast, it is good to go forward for it ;) 

more details about npm 5  here: https://github.com/npm/npm/releases/tag/v5.0.0

**Comment by vazham** [comment]
https://github.com/AngularClass/angular-starter/pull/1790
This commit should fix this issue. It works in npm 3/4/5.

**Comment by almothafar** [comment]
@vazham why you decided to use `--force` not `verify`?

**Comment by vazham** [comment]
You will get error on npm 3 if you will use `npm cache verify`.

**Comment by dbean23** [comment]
None of this has worked for me. I still get

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-02-16T22_41_08_524Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'create-react-app' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose npm-session 944a5f57c0bafb6b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/create-react-app 16ms (from cache)
8 silly pacote tag manifest for create-react-app@latest fetched in 29ms
9 timing stage:loadCurrentTree Completed in 160ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule create-react-app@2.1.5 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/hyperquest 20ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/chalk 23ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/validate-npm-package-name 18ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/tar-pack 22ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/tmp 19ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/cross-spawn 24ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/commander 26ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/semver 24ms (from cache)
25 silly pacote version manifest for hyperquest@2.1.3 fetched in 26ms
26 silly resolveWithNewModule hyperquest@2.1.3 checking installable status
27 http fetch GET 200 https://registry.npmjs.org/fs-extra 28ms (from cache)
28 silly pacote version manifest for chalk@1.1.3 fetched in 31ms
29 silly resolveWithNewModule chalk@1.1.3 checking installable status
30 silly pacote version manifest for validate-npm-package-name@3.0.0 fetched in 26ms
31 silly resolveWithNewModule validate-npm-package-name@3.0.0 checking installable status
32 silly pacote version manifest for tar-pack@3.4.1 fetched in 29ms
33 silly resolveWithNewModule tar-pack@3.4.1 checking installable status
34 silly pacote version manifest for tmp@0.0.33 fetched in 27ms
35 silly resolveWithNewModule tmp@0.0.33 checking installable status
36 silly pacote version manifest for cross-spawn@4.0.2 fetched in 31ms
37 silly resolveWithNewModule cross-spawn@4.0.2 checking installable status
38 silly pacote version manifest for commander@2.18.0 fetched in 33ms
39 silly resolveWithNewModule commander@2.18.0 checking installable status
40 silly pacote version manifest for semver@5.5.1 fetched in 31ms
41 silly resolveWithNewModule semver@5.5.1 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/envinfo 33ms (from cache)
43 silly pacote version manifest for fs-extra@5.0.0 fetched in 35ms
44 silly resolveWithNewModule fs-extra@5.0.0 checking installable status
45 silly pacote version manifest for envinfo@5.11.1 fetched in 35ms
46 silly resolveWithNewModule envinfo@5.11.1 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/ansi-styles 10ms (from cache)
48 http fetch GET 200 https://registry.npmjs.org/strip-ansi 7ms (from cache)
49 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 10ms (from cache)
50 http fetch GET 200 https://registry.npmjs.org/has-ansi 11ms (from cache)
51 http fetch GET 200 https://registry.npmjs.org/supports-color 9ms (from cache)
52 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 14ms
53 silly resolveWithNewModule ansi-styles@2.2.1 checking installable status
54 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 11ms
55 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
56 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 15ms
57 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
58 silly pacote range manifest for has-ansi@^2.0.0 fetched in 15ms
59 silly resolveWithNewModule has-ansi@2.0.0 checking installable status
60 silly pacote range manifest for supports-color@^2.0.0 fetched in 13ms
61 silly resolveWithNewModule supports-color@2.0.0 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/ansi-regex 2ms (from cache)
63 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 3ms
64 silly resolveWithNewModule ansi-regex@2.1.1 checking installable status
65 http fetch GET 200 https://registry.npmjs.org/which 3ms (from cache)
66 http fetch GET 200 https://registry.npmjs.org/lru-cache 5ms (from cache)
67 silly pacote range manifest for which@^1.2.9 fetched in 12ms
68 silly resolveWithNewModule which@1.3.1 checking installable status
69 silly pacote range manifest for lru-cache@^4.0.1 fetched in 15ms
70 silly resolveWithNewModule lru-cache@4.1.5 checking installable status
71 http fetch GET 200 https://registry.npmjs.org/yallist 6ms (from cache)
72 http fetch GET 200 https://registry.npmjs.org/pseudomap 8ms (from cache)
73 silly pacote range manifest for yallist@^2.1.2 fetched in 8ms
74 silly resolveWithNewModule yallist@2.1.2 checking installable status
75 silly pacote range manifest for pseudomap@^1.0.2 fetched in 10ms
76 silly resolveWithNewModule pseudomap@1.0.2 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/isexe 2ms (from cache)
78 silly pacote range manifest for isexe@^2.0.0 fetched in 3ms
79 silly resolveWithNewModule isexe@2.0.0 checking installable status
80 http fetch GET 200 https://registry.npmjs.org/jsonfile 3ms (from cache)
81 http fetch GET 200 https://registry.npmjs.org/universalify 4ms (from cache)
82 http fetch GET 200 https://registry.npmjs.org/graceful-fs 6ms (from cache)
83 silly pacote range manifest for jsonfile@^4.0.0 fetched in 6ms
84 silly resolveWithNewModule jsonfile@4.0.0 checking installable status
85 silly pacote range manifest for universalify@^0.1.0 fetched in 7ms
86 silly resolveWithNewModule universalify@0.1.2 checking installable status
87 silly pacote range manifest for graceful-fs@^4.1.2 fetched in 9ms
88 silly resolveWithNewModule graceful-fs@4.1.15 checking installable status
89 http fetch GET 200 https://registry.npmjs.org/buffer-from 3ms (from cache)
90 http fetch GET 200 https://registry.npmjs.org/duplexer2 3ms (from cache)
91 http fetch GET 200 https://registry.npmjs.org/through2 3ms (from cache)
92 silly pacote range manifest for buffer-from@^0.1.1 fetched in 5ms
93 silly resolveWithNewModule buffer-from@0.1.2 checking installable status
94 silly pacote range manifest for duplexer2@~0.0.2 fetched in 5ms
95 silly resolveWithNewModule duplexer2@0.0.2 checking installable status
96 silly pacote range manifest for through2@~0.6.3 fetched in 5ms
97 silly resolveWithNewModule through2@0.6.5 checking installable status
98 http fetch GET 200 https://registry.npmjs.org/readable-stream 2ms (from cache)
99 silly pacote range manifest for readable-stream@~1.1.9 fetched in 5ms
100 silly resolveWithNewModule readable-stream@1.1.14 checking installable status
101 http fetch GET 200 https://registry.npmjs.org/core-util-is 5ms (from cache)
102 http fetch GET 200 https://registry.npmjs.org/isarray 6ms (from cache)
103 http fetch GET 200 https://registry.npmjs.org/string_decoder 6ms (from cache)
104 http fetch GET 200 https://registry.npmjs.org/inherits 6ms (from cache)
105 silly pacote version manifest for isarray@0.0.1 fetched in 7ms
106 silly resolveWithNewModule isarray@0.0.1 checking installable status
107 silly pacote range manifest for core-util-is@~1.0.0 fetched in 8ms
108 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
109 silly pacote range manifest for string_decoder@~0.10.x fetched in 8ms
110 silly resolveWithNewModule string_decoder@0.10.31 checking installable status
111 silly pacote range manifest for inherits@~2.0.1 fetched in 8ms
112 silly resolveWithNewModule inherits@2.0.3 checking installable status
113 silly pacote range manifest for readable-stream@>=1.0.33-1 <1.1.0-0 fetched in 2ms
114 silly resolveWithNewModule readable-stream@1.0.34 checking installable status
115 http fetch GET 200 https://registry.npmjs.org/xtend 3ms (from cache)
116 silly pacote range manifest for xtend@>=4.0.0 <4.1.0-0 fetched in 4ms
117 silly resolveWithNewModule xtend@4.0.1 checking installable status
118 silly pacote range manifest for readable-stream@^2.1.4 fetched in 4ms
119 silly resolveWithNewModule readable-stream@2.3.6 checking installable status
120 http fetch GET 200 https://registry.npmjs.org/once 10ms (from cache)
121 http fetch GET 200 https://registry.npmjs.org/fstream-ignore 11ms (from cache)
122 http fetch GET 200 https://registry.npmjs.org/uid-number 10ms (from cache)
123 http fetch GET 200 https://registry.npmjs.org/rimraf 10ms (from cache)
124 http fetch GET 200 https://registry.npmjs.org/fstream 13ms (from cache)
125 http fetch GET 200 https://registry.npmjs.org/debug 14ms (from cache)
126 silly pacote range manifest for once@^1.3.3 fetched in 16ms
127 silly resolveWithNewModule once@1.4.0 checking installable status
128 silly pacote range manifest for fstream-ignore@^1.0.5 fetched in 16ms
129 silly resolveWithNewModule fstream-ignore@1.0.5 checking installable status
130 silly pacote range manifest for rimraf@^2.5.1 fetched in 17ms
131 silly resolveWithNewModule rimraf@2.6.3 checking installable status
132 silly pacote range manifest for uid-number@^0.0.6 fetched in 17ms
133 silly resolveWithNewModule uid-number@0.0.6 checking installable status
134 silly pacote range manifest for fstream@^1.0.10 fetched in 20ms
135 silly resolveWithNewModule fstream@1.0.11 checking installable status
136 http fetch GET 200 https://registry.npmjs.org/tar 18ms (from cache)
137 silly pacote range manifest for debug@^2.2.0 fetched in 22ms
138 silly resolveWithNewModule debug@2.6.9 checking installable status
139 silly pacote range manifest for tar@^2.2.1 fetched in 21ms
140 silly resolveWithNewModule tar@2.2.1 checking installable status
141 http fetch GET 200 https://registry.npmjs.org/ms 2ms (from cache)
142 silly pacote version manifest for ms@2.0.0 fetched in 3ms
143 silly resolveWithNewModule ms@2.0.0 checking installable status
144 http fetch GET 200 https://registry.npmjs.org/mkdirp 2ms (from cache)
145 silly pacote range manifest for mkdirp@>=0.5 0 fetched in 3ms
146 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
147 http fetch GET 200 https://registry.npmjs.org/minimist 2ms (from cache)
148 silly pacote version manifest for minimist@0.0.8 fetched in 3ms
149 silly resolveWithNewModule minimist@0.0.8 checking installable status
150 http fetch GET 200 https://registry.npmjs.org/glob 2ms (from cache)
151 silly pacote range manifest for glob@^7.1.3 fetched in 4ms
152 silly resolveWithNewModule glob@7.1.3 checking installable status
153 http fetch GET 200 https://registry.npmjs.org/fs.realpath 4ms (from cache)
154 http fetch GET 200 https://registry.npmjs.org/inflight 5ms (from cache)
155 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 4ms (from cache)
156 http fetch GET 200 https://registry.npmjs.org/minimatch 6ms (from cache)
157 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 7ms
158 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
159 silly pacote range manifest for inflight@^1.0.4 fetched in 7ms
160 silly resolveWithNewModule inflight@1.0.6 checking installable status
161 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 8ms
162 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
163 silly pacote range manifest for minimatch@^3.0.4 fetched in 10ms
164 silly resolveWithNewModule minimatch@3.0.4 checking installable status
165 http fetch GET 200 https://registry.npmjs.org/wrappy 2ms (from cache)
166 silly pacote range manifest for wrappy@1 fetched in 2ms
167 silly resolveWithNewModule wrappy@1.0.2 checking installable status
168 http fetch GET 200 https://registry.npmjs.org/brace-expansion 2ms (from cache)
169 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 5ms
170 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
171 http fetch GET 200 https://registry.npmjs.org/balanced-match 3ms (from cache)
172 http fetch GET 200 https://registry.npmjs.org/concat-map 3ms (from cache)
173 silly pacote range manifest for balanced-match@^1.0.0 fetched in 4ms
174 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
175 silly pacote version manifest for concat-map@0.0.1 fetched in 5ms
176 silly resolveWithNewModule concat-map@0.0.1 checking installable status
177 silly pacote range manifest for isarray@~1.0.0 fetched in 3ms
178 silly resolveWithNewModule isarray@1.0.0 checking installable status
179 silly pacote range manifest for string_decoder@~1.1.1 fetched in 2ms
180 silly resolveWithNewModule string_decoder@1.1.1 checking installable status
181 http fetch GET 200 https://registry.npmjs.org/process-nextick-args 6ms (from cache)
182 http fetch GET 200 https://registry.npmjs.org/safe-buffer 5ms (from cache)
183 http fetch GET 200 https://registry.npmjs.org/util-deprecate 5ms (from cache)
184 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 7ms
185 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
186 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 7ms
187 silly resolveWithNewModule util-deprecate@1.0.2 checking installable status
188 silly pacote range manifest for process-nextick-args@~2.0.0 fetched in 8ms
189 silly resolveWithNewModule process-nextick-args@2.0.0 checking installable status
190 http fetch GET 200 https://registry.npmjs.org/block-stream 1ms (from cache)
191 silly pacote range manifest for block-stream@* fetched in 2ms
192 silly resolveWithNewModule block-stream@0.0.9 checking installable status
193 http fetch GET 200 https://registry.npmjs.org/os-tmpdir 1ms (from cache)
194 silly pacote range manifest for os-tmpdir@~1.0.2 fetched in 2ms
195 silly resolveWithNewModule os-tmpdir@1.0.2 checking installable status
196 http fetch GET 200 https://registry.npmjs.org/builtins 1ms (from cache)
197 silly pacote range manifest for builtins@^1.0.3 fetched in 2ms
198 silly resolveWithNewModule builtins@1.0.3 checking installable status
199 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 261ms
200 timing stage:loadIdealTree Completed in 284ms
201 silly currentTree lib
202 silly idealTree lib
202 silly idealTree └─┬ create-react-app@2.1.5
202 silly idealTree   ├── ansi-regex@2.1.1
202 silly idealTree   ├── ansi-styles@2.2.1
202 silly idealTree   ├── balanced-match@1.0.0
202 silly idealTree   ├── block-stream@0.0.9
202 silly idealTree   ├── brace-expansion@1.1.11
202 silly idealTree   ├── buffer-from@0.1.2
202 silly idealTree   ├── builtins@1.0.3
202 silly idealTree   ├── chalk@1.1.3
202 silly idealTree   ├── commander@2.18.0
202 silly idealTree   ├── concat-map@0.0.1
202 silly idealTree   ├── core-util-is@1.0.2
202 silly idealTree   ├── cross-spawn@4.0.2
202 silly idealTree   ├── debug@2.6.9
202 silly idealTree   ├── duplexer2@0.0.2
202 silly idealTree   ├── envinfo@5.11.1
202 silly idealTree   ├── escape-string-regexp@1.0.5
202 silly idealTree   ├── fs-extra@5.0.0
202 silly idealTree   ├── fs.realpath@1.0.0
202 silly idealTree   ├── fstream-ignore@1.0.5
202 silly idealTree   ├── fstream@1.0.11
202 silly idealTree   ├── glob@7.1.3
202 silly idealTree   ├── graceful-fs@4.1.15
202 silly idealTree   ├── has-ansi@2.0.0
202 silly idealTree   ├── hyperquest@2.1.3
202 silly idealTree   ├── inflight@1.0.6
202 silly idealTree   ├── inherits@2.0.3
202 silly idealTree   ├── isarray@0.0.1
202 silly idealTree   ├── isexe@2.0.0
202 silly idealTree   ├── jsonfile@4.0.0
202 silly idealTree   ├── lru-cache@4.1.5
202 silly idealTree   ├── minimatch@3.0.4
202 silly idealTree   ├── minimist@0.0.8
202 silly idealTree   ├── mkdirp@0.5.1
202 silly idealTree   ├── ms@2.0.0
202 silly idealTree   ├── once@1.4.0
202 silly idealTree   ├── os-tmpdir@1.0.2
202 silly idealTree   ├── path-is-absolute@1.0.1
202 silly idealTree   ├── process-nextick-args@2.0.0
202 silly idealTree   ├── pseudomap@1.0.2
202 silly idealTree   ├── readable-stream@1.1.14
202 silly idealTree   ├── rimraf@2.6.3
202 silly idealTree   ├── safe-buffer@5.1.2
202 silly idealTree   ├── semver@5.5.1
202 silly idealTree   ├── string_decoder@0.10.31
202 silly idealTree   ├── strip-ansi@3.0.1
202 silly idealTree   ├── supports-color@2.0.0
202 silly idealTree   ├─┬ tar-pack@3.4.1
202 silly idealTree   │ ├── isarray@1.0.0
202 silly idealTree   │ ├── readable-stream@2.3.6
202 silly idealTree   │ └── string_decoder@1.1.1
202 silly idealTree   ├── tar@2.2.1
202 silly idealTree   ├─┬ through2@0.6.5
202 silly idealTree   │ └── readable-stream@1.0.34
202 silly idealTree   ├── tmp@0.0.33
202 silly idealTree   ├── uid-number@0.0.6
202 silly idealTree   ├── universalify@0.1.2
202 silly idealTree   ├── util-deprecate@1.0.2
202 silly idealTree   ├── validate-npm-package-name@3.0.0
202 silly idealTree   ├── which@1.3.1
202 silly idealTree   ├── wrappy@1.0.2
202 silly idealTree   ├── xtend@4.0.1
202 silly idealTree   └── yallist@2.1.2
203 silly install generateActionsToTake
204 warn checkPermissions Missing write access to /usr/local/lib/node_modules
205 timing stage:rollbackFailedOptional Completed in 0ms
206 timing stage:runTopLevelLifecycles Completed in 456ms
207 verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
208 verbose cwd /Users/user/Documents/web-development/CJ-LearnReact
209 verbose Darwin 18.2.0
210 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-app"
211 verbose node v10.13.0
212 verbose npm  v6.4.1
213 error path /usr/local/lib/node_modules
214 error code EACCES
215 error errno -13
216 error syscall access
217 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
217 error  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
217 error   stack:
217 error    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
217 error   errno: -13,
217 error   code: 'EACCES',
217 error   syscall: 'access',
217 error   path: '/usr/local/lib/node_modules' }
218 error The operation was rejected by your operating system.
218 error It is likely you do not have the permissions to access this file as the current user
218 error
218 error If you believe this might be a permissions issue, please double-check the
218 error permissions of the file and its containing directories, or try running
218 error the command again as root/Administrator (though this is not recommended).
219 verbose exit [ -13, true ]
